[features]
seeds = false
skip-lint = false
[programs.localnet]
defi_pg = "6uEtFvj1EtCD3oZvAhCR4wW3j1TQv2CaxgMoXyfksqaC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
